pipeline {
    agent any

    environment {
        SONAR_SCANNER = tool 'SonarScanner'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install dependencies') {
            steps {
                dir('lexconnect-frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('lexconnect-frontend') {
                    withSonarQubeEnv('SonarQube') {
                        sh "${SONAR_SCANNER}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('lexconnect-frontend') {
                    sh 'docker build -t lexconnect-frontend .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 4200:80 --name lexconnect-frontend lexconnect-frontend'
            }
        }
    }
}